// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GCTOLS.proto

/*
Package __GCToLs is a generated protocol buffer package.

It is generated from these files:
	GCTOLS.proto

It has these top-level messages:
	AskLogin
	SendMsg
	SendGroupMsg
	NetMsg
	ReadMsg
	LoginResult
	SendGroupResult
*/
package __GCToLs

import proto "github.com/agilab/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd int32

const (
	Cmd_eMsgToLSFromGC_Unknow Cmd = 0
	// 登录相关
	Cmd_eMsgToLSFromGC_AskLogin Cmd = 1
	// 消息相关
	Cmd_eMsgToLSFromGC_SendMsg      Cmd = 160
	Cmd_eMsgToLSFromGC_ReadMsg      Cmd = 161
	Cmd_eMsgToLSFromGC_SendGroupMsg Cmd = 178
	// 消息通知相关
	Cmd_eMsgToGCFromLS_NetMsg Cmd = 208
)

var Cmd_name = map[int32]string{
	0:   "eMsgToLSFromGC_Unknow",
	1:   "eMsgToLSFromGC_AskLogin",
	160: "eMsgToLSFromGC_SendMsg",
	161: "eMsgToLSFromGC_ReadMsg",
	178: "eMsgToLSFromGC_SendGroupMsg",
	208: "eMsgToGCFromLS_NetMsg",
}
var Cmd_value = map[string]int32{
	"eMsgToLSFromGC_Unknow":       0,
	"eMsgToLSFromGC_AskLogin":     1,
	"eMsgToLSFromGC_SendMsg":      160,
	"eMsgToLSFromGC_ReadMsg":      161,
	"eMsgToLSFromGC_SendGroupMsg": 178,
	"eMsgToGCFromLS_NetMsg":       208,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}
func (Cmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AskLogin struct {
	Cmd   Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Plat  string `protobuf:"bytes,2,opt,name=plat" json:"plat,omitempty"`
	Uid   string `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	Login string `protobuf:"bytes,4,opt,name=login" json:"login,omitempty"`
	Pwd   string `protobuf:"bytes,5,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *AskLogin) Reset()                    { *m = AskLogin{} }
func (m *AskLogin) String() string            { return proto.CompactTextString(m) }
func (*AskLogin) ProtoMessage()               {}
func (*AskLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AskLogin) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *AskLogin) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *AskLogin) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AskLogin) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AskLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SendMsg struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Send string `protobuf:"bytes,2,opt,name=send" json:"send,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=recv" json:"recv,omitempty"`
	Plat string `protobuf:"bytes,4,opt,name=plat" json:"plat,omitempty"`
	Data string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *SendMsg) Reset()                    { *m = SendMsg{} }
func (m *SendMsg) String() string            { return proto.CompactTextString(m) }
func (*SendMsg) ProtoMessage()               {}
func (*SendMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendMsg) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *SendMsg) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

func (m *SendMsg) GetRecv() string {
	if m != nil {
		return m.Recv
	}
	return ""
}

func (m *SendMsg) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *SendMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SendGroupMsg struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Send string `protobuf:"bytes,2,opt,name=send" json:"send,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=recv" json:"recv,omitempty"`
	Plat string `protobuf:"bytes,4,opt,name=plat" json:"plat,omitempty"`
	Data string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *SendGroupMsg) Reset()                    { *m = SendGroupMsg{} }
func (m *SendGroupMsg) String() string            { return proto.CompactTextString(m) }
func (*SendGroupMsg) ProtoMessage()               {}
func (*SendGroupMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendGroupMsg) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *SendGroupMsg) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

func (m *SendGroupMsg) GetRecv() string {
	if m != nil {
		return m.Recv
	}
	return ""
}

func (m *SendGroupMsg) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *SendGroupMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type NetMsg struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Send string `protobuf:"bytes,2,opt,name=send" json:"send,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=recv" json:"recv,omitempty"`
	Plat string `protobuf:"bytes,4,opt,name=plat" json:"plat,omitempty"`
	Mid  string `protobuf:"bytes,5,opt,name=mid" json:"mid,omitempty"`
}

func (m *NetMsg) Reset()                    { *m = NetMsg{} }
func (m *NetMsg) String() string            { return proto.CompactTextString(m) }
func (*NetMsg) ProtoMessage()               {}
func (*NetMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NetMsg) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *NetMsg) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

func (m *NetMsg) GetRecv() string {
	if m != nil {
		return m.Recv
	}
	return ""
}

func (m *NetMsg) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *NetMsg) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type ReadMsg struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Send string `protobuf:"bytes,2,opt,name=send" json:"send,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=recv" json:"recv,omitempty"`
	Mid  string `protobuf:"bytes,4,opt,name=mid" json:"mid,omitempty"`
}

func (m *ReadMsg) Reset()                    { *m = ReadMsg{} }
func (m *ReadMsg) String() string            { return proto.CompactTextString(m) }
func (*ReadMsg) ProtoMessage()               {}
func (*ReadMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadMsg) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *ReadMsg) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

func (m *ReadMsg) GetRecv() string {
	if m != nil {
		return m.Recv
	}
	return ""
}

func (m *ReadMsg) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

// 登录返回
type LoginResult struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Uid  string `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	Data string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *LoginResult) Reset()                    { *m = LoginResult{} }
func (m *LoginResult) String() string            { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()               {}
func (*LoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginResult) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *LoginResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LoginResult) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginResult) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 发消息返回
type SendGroupResult struct {
	Cmd  Cmd    `protobuf:"varint,1,opt,name=cmd,enum=GCToLS.Cmd" json:"cmd,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=recv" json:"recv,omitempty"`
	Plat string `protobuf:"bytes,4,opt,name=plat" json:"plat,omitempty"`
	Data string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	Send string `protobuf:"bytes,6,opt,name=send" json:"send,omitempty"`
}

func (m *SendGroupResult) Reset()                    { *m = SendGroupResult{} }
func (m *SendGroupResult) String() string            { return proto.CompactTextString(m) }
func (*SendGroupResult) ProtoMessage()               {}
func (*SendGroupResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SendGroupResult) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_eMsgToLSFromGC_Unknow
}

func (m *SendGroupResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SendGroupResult) GetRecv() string {
	if m != nil {
		return m.Recv
	}
	return ""
}

func (m *SendGroupResult) GetPlat() string {
	if m != nil {
		return m.Plat
	}
	return ""
}

func (m *SendGroupResult) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SendGroupResult) GetSend() string {
	if m != nil {
		return m.Send
	}
	return ""
}

func init() {
	proto.RegisterType((*AskLogin)(nil), "GCToLS.AskLogin")
	proto.RegisterType((*SendMsg)(nil), "GCToLS.SendMsg")
	proto.RegisterType((*SendGroupMsg)(nil), "GCToLS.SendGroupMsg")
	proto.RegisterType((*NetMsg)(nil), "GCToLS.NetMsg")
	proto.RegisterType((*ReadMsg)(nil), "GCToLS.ReadMsg")
	proto.RegisterType((*LoginResult)(nil), "GCToLS.LoginResult")
	proto.RegisterType((*SendGroupResult)(nil), "GCToLS.SendGroupResult")
	proto.RegisterEnum("GCToLS.Cmd", Cmd_name, Cmd_value)
}

func init() { proto.RegisterFile("GCTOLS.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x4b, 0x4e, 0xe3, 0x40,
	0x10, 0x86, 0xa7, 0xc7, 0x8e, 0x93, 0xa9, 0x44, 0x33, 0xad, 0xd6, 0x3c, 0x3c, 0x44, 0x48, 0x91,
	0x57, 0x11, 0x0b, 0x2f, 0x60, 0xc9, 0x0a, 0x2c, 0xe1, 0x8d, 0x03, 0x92, 0x1d, 0x36, 0x6c, 0x22,
	0x27, 0xdd, 0x44, 0x56, 0x62, 0xb7, 0xe5, 0x07, 0x66, 0xc3, 0x2d, 0x38, 0x00, 0x5c, 0x01, 0x89,
	0x7b, 0x70, 0x24, 0xd4, 0xed, 0x47, 0xa2, 0x28, 0x8b, 0x88, 0x87, 0xd8, 0xfd, 0xae, 0x2a, 0xfb,
	0x2b, 0xfd, 0x55, 0x65, 0xe8, 0xd9, 0xd6, 0xf8, 0xc2, 0xf1, 0xcc, 0x38, 0xe1, 0x19, 0x27, 0x9a,
	0x6d, 0x8d, 0xb9, 0xe3, 0x19, 0x05, 0x74, 0x4e, 0xd2, 0x85, 0xc3, 0xe7, 0x41, 0x44, 0xf6, 0x41,
	0x99, 0x85, 0x54, 0x47, 0x03, 0x34, 0xfc, 0x79, 0xd8, 0x35, 0xcb, 0x0a, 0xd3, 0x0a, 0xa9, 0x2b,
	0xe2, 0x84, 0x80, 0x1a, 0x2f, 0xfd, 0x4c, 0xff, 0x3e, 0x40, 0xc3, 0x1f, 0xae, 0xd4, 0x04, 0x83,
	0x92, 0x07, 0x54, 0x57, 0x64, 0x48, 0x48, 0xf2, 0x1b, 0x5a, 0x4b, 0xf1, 0x35, 0x5d, 0x95, 0xb1,
	0xf2, 0x41, 0xd4, 0xc5, 0x05, 0xd5, 0x5b, 0x65, 0x5d, 0x5c, 0x50, 0xe3, 0x16, 0xda, 0x1e, 0x8b,
	0xe8, 0x28, 0x9d, 0xef, 0xc0, 0x4d, 0x59, 0x44, 0x6b, 0xae, 0xd0, 0x22, 0x96, 0xb0, 0xd9, 0x4d,
	0x05, 0x96, 0xba, 0xe9, 0x4f, 0x5d, 0xeb, 0x8f, 0x80, 0x4a, 0xfd, 0xcc, 0xaf, 0xc0, 0x52, 0x1b,
	0x77, 0xd0, 0x13, 0x64, 0x3b, 0xe1, 0x79, 0xfc, 0x05, 0xf8, 0x1c, 0xb4, 0x73, 0x96, 0x7d, 0x32,
	0x18, 0x83, 0x12, 0x06, 0x8d, 0xdf, 0x61, 0x40, 0x8d, 0x29, 0xb4, 0x5d, 0xe6, 0x7f, 0xa4, 0xdf,
	0x15, 0x43, 0x5d, 0x31, 0xae, 0xa1, 0x2b, 0x37, 0xc9, 0x65, 0x69, 0xbe, 0xcc, 0x76, 0xe0, 0xcc,
	0x38, 0x65, 0x35, 0x47, 0xe8, 0x2d, 0xfb, 0x54, 0x5b, 0xa8, 0xae, 0x59, 0x78, 0x8f, 0xe0, 0x57,
	0x33, 0xc2, 0xb7, 0xc3, 0xde, 0x31, 0xc5, 0xc6, 0x24, 0x6d, 0x65, 0xd2, 0xc1, 0x33, 0x02, 0xc5,
	0x0a, 0x29, 0xf9, 0x0f, 0x7f, 0xd8, 0x28, 0x9d, 0x8b, 0x06, 0xce, 0x12, 0x1e, 0xda, 0xd6, 0xe4,
	0x32, 0x5a, 0x44, 0xbc, 0xc0, 0xdf, 0x48, 0x1f, 0xfe, 0x6d, 0xa4, 0xea, 0xeb, 0xc3, 0x88, 0xf4,
	0xe1, 0xef, 0x46, 0xb2, 0xba, 0x10, 0xfc, 0xb0, 0x2d, 0x59, 0x8d, 0x13, 0x3f, 0x22, 0x32, 0x80,
	0xfe, 0x96, 0x37, 0xeb, 0x0d, 0xc7, 0x4f, 0x88, 0xec, 0xd5, 0x3d, 0xd9, 0x96, 0xa8, 0x70, 0xbc,
	0x49, 0xb9, 0x84, 0xf8, 0x05, 0x9d, 0xc2, 0x55, 0xc7, 0x3c, 0x96, 0x86, 0xa5, 0x53, 0x4d, 0xfe,
	0x1e, 0x8e, 0x5e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x1e, 0x78, 0x3c, 0x2e, 0x04, 0x00, 0x00,
}
