// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Head
	Body
	Msg
*/
package protos

import proto "github.com/agilab/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Head struct {
	Version uint32 `protobuf:"fixed32,1,opt,name=version" json:"version,omitempty"`
	Cmd     uint32 `protobuf:"fixed32,2,opt,name=cmd" json:"cmd,omitempty"`
	Len     uint64 `protobuf:"varint,3,opt,name=len" json:"len,omitempty"`
	Encry   uint32 `protobuf:"varint,4,opt,name=encry" json:"encry,omitempty"`
	Ext1    uint32 `protobuf:"fixed32,5,opt,name=ext1" json:"ext1,omitempty"`
	Ext2    uint32 `protobuf:"fixed32,6,opt,name=ext2" json:"ext2,omitempty"`
}

func (m *Head) Reset()                    { *m = Head{} }
func (m *Head) String() string            { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()               {}
func (*Head) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Head) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Head) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Head) GetLen() uint64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Head) GetEncry() uint32 {
	if m != nil {
		return m.Encry
	}
	return 0
}

func (m *Head) GetExt1() uint32 {
	if m != nil {
		return m.Ext1
	}
	return 0
}

func (m *Head) GetExt2() uint32 {
	if m != nil {
		return m.Ext2
	}
	return 0
}

type Body struct {
	Bodylen uint64 `protobuf:"varint,1,opt,name=bodylen" json:"bodylen,omitempty"`
	Data    string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Body) GetBodylen() uint64 {
	if m != nil {
		return m.Bodylen
	}
	return 0
}

func (m *Body) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Msg struct {
	Head *Head `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	Body *Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Msg) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Head)(nil), "protos.Head")
	proto.RegisterType((*Body)(nil), "protos.Body")
	proto.RegisterType((*Msg)(nil), "protos.Msg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xb1, 0x6e, 0x83, 0x30,
	0x10, 0x95, 0xc1, 0x80, 0xb8, 0xb6, 0x52, 0x65, 0x75, 0xf0, 0x68, 0x31, 0x31, 0x21, 0x95, 0xf6,
	0x0b, 0x98, 0xda, 0xa1, 0x8b, 0xff, 0xc0, 0x60, 0x0b, 0x2a, 0x05, 0x1c, 0x61, 0x14, 0x85, 0x35,
	0x9f, 0x92, 0x2f, 0x8d, 0xee, 0x08, 0x51, 0x26, 0xbf, 0xf7, 0xee, 0xde, 0xf3, 0xdd, 0x41, 0x3e,
	0x86, 0xbe, 0x3a, 0xce, 0x7e, 0xf1, 0x22, 0xa5, 0x27, 0x14, 0x17, 0x06, 0xfc, 0xc7, 0x19, 0x2b,
	0x24, 0x64, 0x27, 0x37, 0x87, 0x7f, 0x3f, 0x49, 0xa6, 0x58, 0x99, 0xe9, 0x9d, 0x8a, 0x77, 0x88,
	0xbb, 0xd1, 0xca, 0x88, 0x54, 0x84, 0xa8, 0x1c, 0xdc, 0x24, 0x63, 0xc5, 0x4a, 0xae, 0x11, 0x8a,
	0x0f, 0x48, 0xdc, 0xd4, 0xcd, 0xab, 0xe4, 0x8a, 0x95, 0x6f, 0x7a, 0x23, 0x42, 0x00, 0x77, 0xe7,
	0xe5, 0x53, 0x26, 0x64, 0x25, 0x7c, 0xd7, 0x6a, 0x99, 0x3e, 0xb4, 0xba, 0xf8, 0x06, 0xde, 0x78,
	0xbb, 0xe2, 0x0c, 0xad, 0xb7, 0x2b, 0x66, 0x33, 0xca, 0xde, 0x29, 0xba, 0xac, 0x59, 0x0c, 0x0d,
	0x91, 0x6b, 0xc2, 0xc5, 0x2f, 0xc4, 0x7f, 0xa1, 0x17, 0x0a, 0xf8, 0xe0, 0x8c, 0x25, 0xc7, 0x4b,
	0xfd, 0xba, 0xed, 0x17, 0x2a, 0x5c, 0x4a, 0x53, 0x05, 0x3b, 0x30, 0x87, 0xcc, 0x4f, 0x1d, 0xf8,
	0xa5, 0xa6, 0x4a, 0x93, 0x5c, 0xa3, 0x68, 0x1c, 0xda, 0xed, 0x28, 0x5f, 0xb7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd4, 0x94, 0x49, 0x94, 0x28, 0x01, 0x00, 0x00,
}
